version: 0.2

phases:

  pre_build:

    commands:

      - $(aws ecr get-login --no-include-email --region ap-southeast-1)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"

  build:

    commands:

      - docker build --tag "322549764935.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-demo-ecr-01:${TAG}" .

  post_build:

    commands:

      - docker push "322549764935.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-demo-ecr-01:${TAG}"

      - printf '{"tag":"%s"}' $TAG > build.json

artifacts:

  files: build.json